- platform: kodi
  host: 192.168.2.230
  name: libre_bedroom_main
  port: 8080
  username: !secrets kodi.username
  password: !secrets kodi.password
  enable_websocket: true
- platform: kodi
  host: 192.168.2.231
  name: libre_livingroom
  port: 8080
  username: !secrets kodi.username
  password: !include secrets kodi.password
  enable_websocket: true

